// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yqHSMpQ27dz0jKvxPyE4ayiLw3VSDa4',
    appId: '1:146390824855:web:69acc61cd2c00e8fa436d2',
    messagingSenderId: '146390824855',
    projectId: 'appforge-app',
    authDomain: 'appforge-app.firebaseapp.com',
    storageBucket: 'appforge-app.firebasestorage.app',
    measurementId: 'G-L21XVHLQVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoWgkc8PMh76gNglrs2fsvPZHty_o4La0',
    appId: '1:146390824855:android:7ab0ac52a2c76597a436d2',
    messagingSenderId: '146390824855',
    projectId: 'appforge-app',
    storageBucket: 'appforge-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCrTfMOJCDQZUgMgYFHn-_mdJ0uOyAYQ',
    appId: '1:146390824855:ios:6a6067462fc5656fa436d2',
    messagingSenderId: '146390824855',
    projectId: 'appforge-app',
    storageBucket: 'appforge-app.firebasestorage.app',
    iosBundleId: 'com.hejitech.appforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCrTfMOJCDQZUgMgYFHn-_mdJ0uOyAYQ',
    appId: '1:146390824855:ios:6a6067462fc5656fa436d2',
    messagingSenderId: '146390824855',
    projectId: 'appforge-app',
    storageBucket: 'appforge-app.firebasestorage.app',
    iosBundleId: 'com.hejitech.appforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8yqHSMpQ27dz0jKvxPyE4ayiLw3VSDa4',
    appId: '1:146390824855:web:9a57e69797493932a436d2',
    messagingSenderId: '146390824855',
    projectId: 'appforge-app',
    authDomain: 'appforge-app.firebaseapp.com',
    storageBucket: 'appforge-app.firebasestorage.app',
    measurementId: 'G-YYS51D03B7',
  );
}
