import 'package:flutter/material.dart';
import 'package:flutter_markdown_plus/flutter_markdown_plus.dart';

enum LegalNoticeType {
  privacyNotice,
  userAgreement,
}

class LegalNoticeScreen extends StatelessWidget {
  final LegalNoticeType type;

  const LegalNoticeScreen({
    super.key,
    required this.type,
  });

  String _getTitle() {
    switch (type) {
      case LegalNoticeType.privacyNotice:
        return 'Privacy Notice';
      case LegalNoticeType.userAgreement:
        return 'User Agreement';
    }
  }

  String _getContent() {
    switch (type) {
      case LegalNoticeType.privacyNotice:
        return '''
# Privacy Notice for MicroForge

**Last Updated: March 18, 2026**

Welcome to MicroForge. We are committed to protecting your privacy and providing a transparent experience when you use our platform to "forge" micro-apps.

## 1. Information We Collect

### 1.1 Account Information
When you create an account, we collect your email address and display name via Firebase Authentication. This is necessary to manage your access and identify your forged apps.

### 1.2 User-Generated Content
We store your conversations with the MicroForge AI and the code for the micro-apps you forge in Cloud Firestore. This allows you to access your history and apps across different sessions.

### 1.3 Device Information
Micro-apps you forge may request access to device features such as:
- **Geolocation:** To provide location-aware functionality.
- **Accelerometer:** To enable motion and tilt-based interactions.
- **Notifications:** To keep you informed of background tasks.

Access to these features is strictly controlled by your device's permission system and the settings within the MicroForge app.

## 2. How We Use Your Information

### 2.1 Service Provisioning
We use your data to provide the core functionality of MicroForge, including:
- Generating micro-apps using the Gemini AI (via Firebase AI Logic).
- Storing and retrieving your micro-apps and conversation history.
- Executing background tasks for your forged apps.

### 2.2 AI Generation
Your prompts and existing app context are sent to the Gemini API (Google AI) to generate and enhance micro-apps. This data is handled according to Google's generative AI privacy policies.

## 3. Data Sharing
We do not sell your personal data. We share information only with service providers (like Google/Firebase) necessary to operate the platform or as required by law.

## 4. Your Control and Rights
- **Access and Portability:** You can view your forged apps and history at any time.
- **Correction:** You can update your display name in the Settings screen.
- **Deletion:** You can delete your account and all associated data (conversations, forged apps, profile) permanently from the Settings screen.

## 5. Security
We use industry-standard security measures provided by Firebase to protect your data. However, no method of transmission or storage is 100% secure.

## 6. Contact Us
If you have any questions about this Privacy Notice, please contact us through the feedback mechanism in the app.
''';
      case LegalNoticeType.userAgreement:
        return '''
# User Agreement for MicroForge

**Last Updated: March 18, 2026**

By using MicroForge, you agree to the following terms and conditions. Please read them carefully.

## 1. Acceptance of Terms
By creating an account or using any part of the MicroForge platform, you agree to be bound by this User Agreement. If you do not agree, you may not use the service.

## 2. The Service
MicroForge is a "Vibe Coding" platform that uses AI to help users create and run functional micro-apps. The platform is provided for your personal and professional use as a tool for rapid prototyping and app forging.

## 3. User Responsibility

### 3.1 Content Ownership
You retain ownership of the prompts you provide and the micro-apps you forge. However, you are solely responsible for the content, behavior, and legality of these micro-apps.

### 3.2 Prohibited Use
You agree NOT to use MicroForge to:
- Generate or distribute harmful, illegal, or malicious code.
- Violate the privacy or intellectual property rights of others.
- Harass, threaten, or impersonate others.
- Circumvent the platform's security or AI safety filters.

### 3.3 AI-Generated Code
The code generated by MicroForge is produced by an AI model. While we strive for quality, we do not guarantee the correctness, safety, or performance of the generated code. You must review and test all forged apps before relying on them.

## 4. Platform Rights
We reserve the right to:
- Modify or discontinue the service at any time.
- Terminate your access for violations of this agreement.
- Update this agreement. Continued use after updates constitutes acceptance.

## 5. Disclaimers and Limitation of Liability
MICROFORGE IS PROVIDED "AS IS" AND "AS AVAILABLE." WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED. WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.

## 6. Termination
You may terminate this agreement at any time by deleting your account. Upon deletion, all your data will be permanently removed from our active databases.

## 7. Governing Law
This agreement is governed by the laws of the jurisdiction in which the service provider is established, without regard to its conflict of law principles.
''';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_getTitle()),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: MarkdownBody(
          data: _getContent(),
          selectable: true,
        ),
      ),
    );
  }
}
